---
template_variables:
  book_title: VMware Tanzu Documentation
  book_title_short: VMware Tanzu Docs
  title: <span class="title-deemph">VMware Tanzu</span> Documentation
  title_image: images/icon-p-green.jpg
  hero_text: "Detailed documentation to help you install, understand, and succeed with VMware's enterprise-grade software."

  tile_name: Metric Store

  product_full: Metric Store
  product_short: Metric Store
  product_abbr: Metric Store #(do not use)

  product_network: VMware Tanzu Network

  path_to_partials:

  app_runtime_full: VMware Tanzu Application Service for VMs
  app_runtime_abbr: TAS for VMs

  k8s_runtime_full: Tanzu Kubernetes Grid Integrated Edition
  k8s_runtime_abbr: TKGI

  windows_runtime_full: VMware Tanzu Application Service for VMs &#91;Windows&#93;
  windows_runtime_abbr: TAS for VMs &#91;Windows&#93;

  segment_runtime_full: Isolation Segment

  ops_manager: Tanzu Operations Manager

  product_url: https://network.tanzu.vmware.com/products/
  product_link: <div class="header-item"><a href="https://network.tanzu.vmware.com/products/pivotal-cf">Back to Product Page</a></div>

  api_version: 235
  gtm_account_id: GTM-MM86KCJ

  use_global_header: true
  global_header_product_href: https://network.tanzu.vmware.com/
  global_header_product_link_text: Downloads
